auto_select_gpus: ${machine.trainer.auto_select_gpus}
benchmark: False
max_epochs: 1001
gpus: ${machine.trainer.gpus}
log_every_n_steps: 1
deterministic: False
detect_anomaly: False
enable_progress_bar: True
check_val_every_n_epoch: 100
limit_train_batches: 1.0
limit_val_batches: 1.0
